#!/bin/bash

#
# based on https://github.com/PDAL/PDAL/tree/master/scripts/docker
#

apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 --keyserver-options http-proxy="$http_proxy" 16126D3A3E5C1192

apt-get update -qq

apt-get -qq remove postgis

apt-get update

apt-get install -y --fix-missing --no-install-recommends \
        build-essential \
        ca-certificates \
        cmake \
        curl \
        gfortran \
        git \
        libarmadillo-dev \
        libarpack2-dev \
        libflann-dev \
        libhdf5-serial-dev \
        liblapack-dev \
        libtiff5-dev \
        openssh-client \
        python-dev \
        python-numpy \
        python-software-properties \
        software-properties-common \
        wget \
        automake \
        libtool \
        libspatialite-dev \
        libsqlite3-mod-spatialite \
        libhdf5-dev \
        subversion \
        libjsoncpp-dev \
        libboost-filesystem1.58-dev \
        libboost-iostreams1.58-dev \
        libboost-program-options1.58-dev \
        libboost-system1.58-dev \
        libboost-thread1.58-dev \
        subversion \
        clang \
        clang-3.6 \
        libproj-dev \
        libc6-dev \
        libnetcdf-dev \
        libjasper-dev \
        libpng-dev \
        libjpeg-dev \
        libgif-dev \
        libwebp-dev \
        libhdf4-alt-dev \
        libhdf5-dev \
        libpq-dev \
        libxerces-c-dev \
        unixodbc-dev \
        libsqlite3-dev \
        libgeos-dev \
        libmysqlclient-dev \
        libltdl-dev \
        libcurl4-openssl-dev \
        libspatialite-dev \
        libdap-dev\
        cython \
        python-pip \
        libgdal1-dev \
        gdal-bin \
        libpcl-dev \
        time \
        libhpdf-dev \
        python-setuptools \
        libgeos++-dev \
        libhpdf-dev \
        unzip \
        libopenscenegraph-dev

update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.6 20 \
 && update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.6 20

mkdir -p /usr/local/var/vdatum
mkdir -p /usr/local/share/proj

cd /usr/local/var/vdatum \
    && wget http://download.osgeo.org/proj/vdatum/usa_geoid2012.zip \
    && unzip -j -u usa_geoid2012.zip -d /usr/local/share/proj \
    && wget http://download.osgeo.org/proj/vdatum/usa_geoid2009.zip \
    && unzip -j -u usa_geoid2009.zip -d /usr/local/share/proj \
    && wget http://download.osgeo.org/proj/vdatum/usa_geoid2003.zip  \
    && unzip -j -u usa_geoid2003.zip -d /usr/local/share/proj \
    && wget http://download.osgeo.org/proj/vdatum/usa_geoid1999.zip  \
    && unzip -j -u usa_geoid1999.zip -d /usr/local/share/proj \
    && wget http://download.osgeo.org/proj/vdatum/vertcon/vertconc.gtx  \
    && mv vertconc.gtx /usr/local/share/proj \
    && wget http://download.osgeo.org/proj/vdatum/vertcon/vertcone.gtx  \
    && mv vertcone.gtx /usr/local/share/proj \
    && wget http://download.osgeo.org/proj/vdatum/vertcon/vertconw.gtx  \
    && mv vertconw.gtx /usr/local/share/proj \
    && wget http://download.osgeo.org/proj/vdatum/egm96_15/egm96_15.gtx  \
    && mv egm96_15.gtx /usr/local/share/proj \
    && wget http://download.osgeo.org/proj/vdatum/egm08_25/egm08_25.gtx  \
    && mv egm08_25.gtx /usr/local/share/proj \
    && rm -rf /usr/local/var/vdatum

cd /usr/local/src

git clone https://github.com/hobu/nitro \
    && cd nitro \
    && mkdir build \
    && cd build \
    && cmake \
        -DCMAKE_INSTALL_PREFIX=/usr \
        .. \
    && make \
    && make install

cd /usr/local/src

git clone https://github.com/LASzip/LASzip.git laszip \
    && cd laszip \
    && git checkout e7065cbc5bdbbe0c6e50c9d93d1cd346e9be6778 \
    && mkdir build \
    && cd build \
    && cmake \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE="Release" \
        .. \
    && make \
    && make install

cd /usr/local/src

git clone https://github.com/hobu/hexer.git \
    && cd hexer \
    && mkdir build \
    && cd build \
    && cmake \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE="Release" \
        .. \
    && make \
    && make install

cd /usr/local/src

git clone  https://github.com/hobu/laz-perf.git \
    && cd laz-perf \
    && mkdir build \
    && cd build \
    && cmake \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE="Release" \
        .. \
    && make \
    && make install

cd /usr/local/src

wget http://bitbucket.org/eigen/eigen/get/3.2.7.tar.gz \
        && tar -xvf 3.2.7.tar.gz \
        && cp -R eigen-eigen-b30b87236a1b/Eigen/ /usr/include/Eigen/ \
        && cp -R eigen-eigen-b30b87236a1b/unsupported/ /usr/include/unsupported/ \
        && rm -rf /3.2.7.tar.gz

cd /usr/local/src

svn co -r 2691 \
    --config-option servers:global:http-proxy-host="$http_proxy_host" \
    --config-option servers:global:http-proxy-port="$http_proxy_port" \
    https://svn.osgeo.org/metacrs/geotiff/trunk/libgeotiff/ \
    && cd libgeotiff \
    && ./autogen.sh \
    && ./configure --prefix=/usr \
    && make \
    && make install

cd /usr/local/src

git clone --depth 1 --branch v0.4.6 https://github.com/gadomski/fgt.git \
    && cd fgt \
    && cmake . \
        -DWITH_TESTS=OFF \
        -DBUILD_SHARED_LIBS=ON \
        -DEIGEN3_INCLUDE_DIR=/usr/include \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
    && make \
    && make install

cd /usr/local/src

git clone --depth 1 --branch v0.5.1 https://github.com/gadomski/cpd.git \
    && cd cpd \
    && cmake . \
        -DWITH_TESTS=OFF \
        -DWITH_JSONCPP=OFF \
        -DWITH_FGT=ON \
        -DWITH_STRICT_WARNINGS=OFF \
        -DWITH_DOCS=OFF \
        -DEIGEN3_INCLUDE_DIR=/usr/include \
        -DBUILD_SHARED_LIBS=ON \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
    && make \
    && make install

cd /usr/local/src

git clone https://github.com/ninja-build/ninja.git \
    && cd ninja \
    && ./configure.py --bootstrap \
    && cp ninja /usr/bin

cd /usr/local/src

echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
    add-apt-repository -y ppa:webupd8team/java && \
    apt-get update && \
    apt-get install -y oracle-java8-installer

ln -s /usr/lib/x86_64-linux-gnu/libvtkCommonCore-6.2.so /usr/lib/libvtkproj4.so

add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y \
    && apt-get update \
    && apt-get install -y mbsystem mbsystem-dev

apt-get install -y --fix-missing --no-install-recommends \
        libhpdf-dev \
        python-all-dev \
        python-numpy \
        libsqlite3-mod-spatialite
