#!/bin/bash

cmake \
  -DBUILD_PLUGIN_CPD=OFF \
  -DBUILD_PLUGIN_MBIO=ON \
  -DBUILD_PLUGIN_GREYHOUND=OFF \
  -DBUILD_PLUGIN_HEXBIN=OFF \
  -DBUILD_PLUGIN_ICEBRIDGE=OFF \
  -DBUILD_PLUGIN_MRSID=OFF \
  -DBUILD_PLUGIN_NITF=OFF \
  -DBUILD_PLUGIN_OCI=OFF \
  -DBUILD_PLUGIN_PCL=ON \
  -DBUILD_PLUGIN_PGPOINTCLOUD=OFF \
  -DBUILD_PLUGIN_SQLITE=OFF \
  -DBUILD_PLUGIN_RIVLIB=OFF \
  -DBUILD_PLUGIN_PYTHON=ON \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DENABLE_CTEST=OFF \
  -DWITH_LAZPERF=ON \
  -DWITH_LASZIP=ON \
  -DWITH_TESTS=ON \
  -DWITH_PDAL_JNI=ON \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_PLUGIN_MATLAB=ON \
  -DMATLAB_MEX_LIBRARY=/matlab/bin/glnxa64/libmex.so \
  -DMATLAB_MAT_LIBRARY=/matlab/bin/glnxa64/libmat.so \
  -DMATLAB_MX_LIBRARY=/matlab/bin/glnxa64/libmx.so \
  -DMATLAB_INCLUDE_DIR=/matlab/extern/include \
  -DMATLAB_ENG_LIBRARY=/matlab/bin/glnxa64/libeng.so \
  . \
&& make install \
&& make -j 5 \
